# Web site staging services:
staging:
  profile: test  # This will publish at https://infrastructure-test.staged.apache.org. Omit profile for infrastructure.staged.a.o
  whoami: master # branch protection. If whoami does not match current branch, payload is ignored. 

publish:
  whoami: asf-site

github:
  description: "Testing .asf.yaml and such"
  labels:
    - gnomes
    - ponies

