# Web site staging services:
staging:
  profile: test  # This will publish at https://infrastructure-test.staged.apache.org. Omit profile for infrastructure.staged.a.o
  whoami: master # branch protection. If whoami does not match current branch, payload is ignored. 
  foo: trigger

publish:
  whoami: asf-site

github:
  description: "Test repository for the .asf.yaml features"
  labels:
    - infrastructure
    - apache
    - development
    - github
